// UI action types
export const UI_START_LOADING = 'UI_START_LOADING';
export const UI_STOP_LOADING = 'UI_STOP_LOADING';
export const USER_UI_START_LOADING = 'USER_UI_START_LOADING';
export const USER_UI_STOP_LOADING = 'USER_UI_STOP_LOADING';
export const VENDORS_UI_START_LOADING = 'VENDORS_UI_START_LOADING';
export const VENDORS_UI_STOP_LOADING = 'VENDORS_UI_STOP_LOADING';
export const VENDORS_MENU_UI_START_LOADING = 'VENDORS_MENU_UI_START_LOADING';
export const VENDORS_MENU_UI_STOP_LOADING = 'VENDORS_MENU_UI_STOP_LOADING';
export const CART_UI_START_LOADING = 'CART_UI_START_LOADING';
export const CART_UI_STOP_LOADING = 'CART_UI_STOP_LOADING';
export const ORDERS_UI_START_LOADING = 'ORDERS_UI_START_LOADING';
export const ORDERS_UI_STOP_LOADING = 'ORDERS_UI_STOP_LOADING';
export const ORDER_CHAT_UI_START_LOADING = 'ORDER_CHAT_UI_START_LOADING';
export const ORDER_CHAT_UI_STOP_LOADING = 'ORDER_CHAT_UI_STOP_LOADING';
export const PROMOS_UI_START_LOADING = 'PROMOS_UI_START_LOADING';
export const PROMOS_UI_STOP_LOADING = 'PROMOS_UI_STOP_LOADING';
export const RE_INITIATE_ORDER_UI_START_LOADING =
  'RE_INITIATE_ORDER_UI_START_LOADING';
export const RE_INITIATE_ORDER_UI_STOP_LOADING =
  'RE_INITIATE_ORDER_UI_STOP_LOADING';
export const CATEGORY_UI_START_LOADING = 'CATEGORY_UI_START_LOADING';
export const CATEGORY_UI_STOP_LOADING = 'CATEGORY_UI_STOP_LOADING';
export const BRANCH_UI_START_LOADING = 'BRANCH_UI_START_LOADING';
export const BRANCH_UI_STOP_LOADING = 'BRANCH_UI_STOP_LOADING';
export const CANCEL_UI_START_LOADING = 'CANCEL_UI_START_LOADING';
export const CANCEL_UI_STOP_LOADING = 'CANCEL_UI_STOP_LOADING';

// Authentication action types
export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';

// User action types
export const SET_USER = 'SET_USER';
export const SET_USER_ADDRESS = 'SET_USER_ADDRESS';

// Vendor action types
export const SET_VENDORS = 'SET_VENDORS';
export const SET_VENDOR_MENUS = 'SET_VENDOR_MENUS';
export const SET_MENUS = 'SET_MENUS';
export const SET_CATEGORIES = 'SET_CATEGORIES';

// Consumer cart action types
export const SET_CART = 'SET_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const DELETE_CART = 'DELETE_CART';
export const SET_CHECKOUT_INFO = 'SET_CHECKOUT_INFO';

// Consumer order action types
export const SET_ORDERS = 'SET_ORDERS';
export const SET_SINGLE_ORDER = 'SET_SINGLE_ORDER';

// Chat action types
export const SET_ORDER_CHAT = 'SET_ORDER_CHAT';
export const SET_CHATS = 'SET_CHATS';

// Promo code action types
export const SET_PROMO_CODES = 'SET_PROMO_CODES';

// Branch action types
export const SET_BRANCHES = 'SET_BRANCHES';

// RESETS
export const RESET_UI = 'RESET_UI';
export const RESET_AUTH = 'RESET_AUTH';
export const RESET_USER = 'RESET_USER';
export const RESET_VENDORS = 'RESET_VENDORS';
export const RESET_CART = 'RESET_CART';
export const RESET_ORDERS = 'RESET_ORDERS';
export const RESET_ORDER_CHAT = 'RESET_ORDER_CHAT';
export const RESET_PROMO_CODES = 'RESET_PROMO_CODES';
export const RESET_BRANCHES = 'RESET_BRANCHES';
